import { useState } from 'react'
import { Bell, CaretDown, CheckCircle, CircleNotch, ClipboardText, Cube, FileText, GearSix, House, Leaf, LockKey, MagnifyingGlass, Plus, QrCode, ShieldCheck, Sparkle, TrendUp, Users, X } from '@phosphor-icons/react'
import { QRCodeSVG } from 'qrcode.react'
import { Workspace } from './workspaces'
import './styles.css'

const headers = { 'Content-Type': 'application/json', 'x-viewer-role': 'admin', 'x-enterprise-id': 'ENT-1000' }
const nav = [['总览看板',House],['产品管理',Cube],['数据管理',FileText],['标识管理',ShieldCheck],['生命周期评估',TrendUp],['链上存证',LockKey],['权限管理',Users],['系统设置',GearSix]]
const metrics = [{id:'materialRatio',name:'材料构成',value:'76%',note:'再生材料占比',icon:Cube},{id:'manufacturingEnergy',name:'制造能耗',value:'42',note:'kWh / 台',icon:TrendUp},{id:'recycleRate',name:'回收循环',value:'88%',note:'可回收率',icon:Leaf},{id:'useEfficiency',name:'使用效率',value:'91%',note:'循环效率',icon:Sparkle}]
const process = (issued, labelId) => [['数据提交','已完成','2026-07-24 09:42','0x8f3a…7c21',FileText],['沙箱计算','已完成','2026-07-24 09:43','0x4d92…9ab0',CircleNotch],['演示链存证','PENDING','等待链上确认','0x0000…0000',LockKey],['标识签发',issued?'演示环境已签发':'待签发',issued?labelId:'依赖链上确认',issued?labelId:'—',ShieldCheck]]

export function App(){
 const [active,setActive]=useState('总览看板'),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verify,setVerify]=useState(''),[result,setResult]=useState(''),[label,setLabel]=useState({id:'ECO-HES-0842',score:'84.2',level:'A'})
 async function evaluate(e){e.preventDefault();setBusy(true);setError('');const productName=new FormData(e.currentTarget).get('productName');try{let r=await fetch('/api/eco/algorithms',{headers});if(!r.ok)throw Error('算法列表读取失败');const list=await r.json();const algorithms=list.data||list.items||list;let id=Array.isArray(algorithms)&&algorithms.find(a=>a.name==='生态设计评价算法'&&a.status==='ACTIVE')?.id;if(!id){id=`eco-hes-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;r=await fetch('/api/eco/algorithms',{method:'POST',headers,body:JSON.stringify({id,version:'2.4',name:'生态设计评价算法',metrics:metrics.map((m,i)=>({id:m.id,name:m.name,inputKey:m.id,weight:.25,min:0,max:100,direction:m.id==='manufacturingEnergy'?'LOWER_IS_BETTER':'HIGHER_IS_BETTER',unit:i===1?'kWh':'%'}))})});if(!r.ok)throw Error('算法注册失败');r=await fetch(`/api/eco/algorithms/${id}/status`,{method:'PATCH',headers,body:JSON.stringify({status:'ACTIVE'})});if(!r.ok)throw Error('算法启用失败')}r=await fetch('/api/eco/evaluations',{method:'POST',headers,body:JSON.stringify({algorithmId:id,product:{productId:'HES-1000',productName,enterpriseId:'ENT-1000',attributes:{materialRatio:76,manufacturingEnergy:42,useEfficiency:91,recycleRate:88},sensitiveFields:[]}})});const task=(await r.json()).data?.id;if(!r.ok||!task)throw Error('评价提交失败');for(const endpoint of ['execute','issue']){r=await fetch(`/api/eco/evaluations/${task}/${endpoint}`,{method:'POST',headers,body:'{}'});if(!r.ok)throw Error(endpoint==='execute'?'沙箱计算失败':'标识签发失败')}const issued=(await r.json()).data;if(!issued?.id)throw Error('标识签发未返回编号');setLabel({id:issued.id,score:String(issued.score??'84.2'),level:issued.level??'A'});setModal(false)}catch(x){setError(x.message||'创建失败，请稍后重试')}finally{setBusy(false)}}
 async function verifyLabel(e){e.preventDefault();if(!verify)return;try{const r=await fetch(`/api/eco/verify/${encodeURIComponent(verify)}`,{headers});const body=await r.json().catch(()=>({}));const state=body?.data?.ledgerState||body?.data?.chainStatus||'PENDING';setResult(r.ok?`记录存在且本地完整性校验通过；链上仍为 ${state}`:'未找到对应标识，请检查编号')}catch{setResult('验证服务暂不可用')}}
 const overview = <><section className="intro"><div><p>PRODUCT LIFECYCLE ASSESSMENT</p><h1>氢能储能一体机 HES-1000</h1><span>产品编号 HES-2024-1000 · 生态设计数字标识</span></div><button><MagnifyingGlass/>查看产品档案</button></section><div className="layout"><section className="center"><article className="lifecycle"><div className="life-head"><span><Sparkle weight="fill"/>生命周期评价</span><small>GreenCycle v2.4 · 本地沙箱</small></div><div className="life-grid">{metrics.map((m,i)=>{const I=m.icon;return <div className={`life-card c${i}`} key={m.id}><I weight="fill"/><p>{m.name}</p><b>{m.value}</b><small>{m.note}</small></div>})}<div className="product"><img src="/assets/hes-1000.png"/><div className="score"><small>生态设计评分</small><strong>{label.score}</strong><b>{label.level}</b></div></div></div></article><article className="process"><h2>可信处理流程</h2><div>{process(label.id!=='ECO-HES-0842',label.id).map(([name,status,time,hash,I])=><section key={name}><span className={status==='PENDING'?'wait':'done'}><I weight="fill"/></span><h3>{name}</h3><b className={status==='PENDING'?'orange':''}>{status}</b><p>{time}</p><code>{hash}</code></section>)}</div></article></section><aside className="trust"><div className="trust-title"><div><Leaf weight="fill"/><p>生态设计数字标识<strong>Digital Eco Label</strong></p></div><span>演示版</span></div><div className="trust-score"><small>综合生态等级</small><b>{label.level}</b><strong>{label.score}<em>/100</em></strong><p>本地沙箱评分</p></div><div className="qr"><QRCodeSVG value={`${window.location.origin}/verify/${label.id}`} size={92}/><p>扫码验证标识<br/><b>{label.id}</b></p><QrCode/></div><h3>完整性校验</h3><div className="checks">{['算法版本可追溯','产品数据已校验','计算结果可复现','权限范围已声明'].map(x=><p key={x}><CheckCircle weight="fill"/>{x}</p>)}</div><div className="chain"><LockKey weight="fill"/><p><b>演示链状态：PENDING</b><small>本地内存记录，未链上确认</small></p></div><h3>权限范围</h3><div className="scopes"><span>公开</span><span>合作伙伴</span><span>企业内部</span><span>监管机构</span></div><form onSubmit={verifyLabel}><input value={verify} onChange={e=>setVerify(e.target.value)} placeholder="输入标识编号验证"/><button>验证</button></form>{result&&<small className="verify">{result}</small>}</aside></div></>
 return <div className="shell"><aside><div className="brand"><Leaf weight="fill"/>生态设计<small>DIGITAL LABEL</small></div><p className="side-title">生态设计数字标识</p><nav>{nav.map(([n,I])=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}><I weight={active===n?'fill':'regular'}/>{n}</button>)}</nav><div className="user"><span>林</span><p>林海生<small>生态管理员</small></p><CaretDown/></div></aside><main><header><b>{active}</b><div><span className="pill good"><CheckCircle weight="fill"/>本地沙箱正常</span><span className="pill pending"><CircleNotch/>演示链 PENDING</span><button className="bell"><Bell/></button><button className="new" onClick={()=>setModal(true)}><Plus/>新建评价</button></div></header>{active==='总览看板'?overview:<Workspace active={active} label={label} onEvaluate={()=>setModal(true)}/>}</main>{modal&&<div className="backdrop"><form className="modal" onSubmit={evaluate}><button type="button" onClick={()=>setModal(false)}><X/></button><p>NEW ECO EVALUATION</p><h2>新建生态评价</h2><span>将按可信处理流程提交、沙箱计算并请求签发标识。</span><label>产品名称<input name="productName" defaultValue="氢能储能一体机 HES-1000" required/></label>{error&&<b className="error">{error}</b>}<button className="create" disabled={busy}>{busy?<><CircleNotch className="spin"/>处理中…</>:<><Sparkle weight="fill"/>创建并签发</>}</button></form></div>}</div>}
export default App
