import { useEffect, useMemo, useState } from 'react'
import { Archive, ArrowClockwise, CheckCircle, ClipboardText, Copy, Cube, Database, Eye, FileText, FloppyDisk, Funnel, GearSix, Info, Leaf, LockKey, MagnifyingGlass, Plus, QrCode, SealCheck, ShieldCheck, SlidersHorizontal, Sparkle, Trash, TrendUp, UploadSimple, Users, WarningCircle, XCircle } from '@phosphor-icons/react'
import { QRCodeSVG } from 'qrcode.react'

const headers = { 'Content-Type': 'application/json', 'x-viewer-role': 'admin', 'x-enterprise-id': 'ENT-1000' }
const productRows = [
  { id: 'HES-1000', name: '氢能储能一体机 HES-1000', type: '能源装备', state: '评价中', score: '84.2', updated: '今天 09:43' },
  { id: 'PCS-220', name: '模块化储能变流器 PCS-220', type: '能源装备', state: '待补数', score: '—', updated: '昨天 16:20' },
  { id: 'MFC-08', name: '燃料电池控制器 MFC-08', type: '控制设备', state: '已归档', score: '79.6', updated: '07-22 14:06' },
]
const dataPacks = [
  ['材料与部件清单', '48 个字段', 100, '内部', '已校验', Database],
  ['制造过程与能耗', '26 个字段', 92, '敏感', '待补充', TrendUp],
  ['运输与使用效率', '19 个字段', 100, '合作伙伴', '已校验', FileText],
  ['回收与处置路径', '15 个字段', 81, '内部', '待补充', Archive],
]
const fallbackTasks = [{ id: 'EVA-240724-01', productName: '氢能储能一体机 HES-1000', algorithmVersion: 'GreenCycle v2.4', status: 'COMPLETED', score: 84.2, updatedAt: '2026-07-24 09:43' }, { id: 'EVA-240723-08', productName: '模块化储能变流器 PCS-220', algorithmVersion: 'GreenCycle v2.4', status: 'DRAFT', score: null, updatedAt: '2026-07-23 16:20' }]
const fallbackLabels = [{ id: 'ECO-HES-0842', productName: '氢能储能一体机 HES-1000', score: 84.2, level: 'A', status: 'PENDING', issuedAt: '2026-07-24 09:43' }]

function PageHead({ eyebrow, title, description, action, children }) {
  return <section className="workspace-head"><div><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></div><div className="workspace-action">{children}{action}</div></section>
}
function Notice({ children, kind = 'success' }) { const I = kind === 'success' ? CheckCircle : WarningCircle; return <div className={`notice ${kind}`}><I weight="fill" />{children}</div> }
function Empty({ icon: I = FileText, title, detail, action }) { return <div className="empty"><I weight="duotone" /><b>{title}</b><p>{detail}</p>{action}</div> }
function Tag({ children, state = 'neutral' }) { return <span className={`tag ${state}`}>{children}</span> }
function normalizeList(body) { return Array.isArray(body) ? body : body?.data || body?.items || [] }
function normalizeLabel(item) {
  const id = item?.id || item?.labelId
  return id ? {...item, id} : null
}

function Products({ onEvaluate }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('全部'); const [selected, setSelected] = useState(productRows[0]); const [feedback, setFeedback] = useState('')
  const rows = productRows.filter(p => (filter === '全部' || p.state === filter) && `${p.name}${p.id}`.toLowerCase().includes(query.toLowerCase()))
  return <><PageHead eyebrow="PRODUCT REGISTER" title="产品管理" description="建立产品台账、维护状态，并从产品详情进入生态评价。" action={<button className="primary" onClick={() => setFeedback('演示产品草稿已创建；请继续补齐数据包。')}><Plus weight="bold" />新建产品</button>} />
    {feedback && <Notice>{feedback}</Notice>}<section className="workspace-grid products-grid"><article className="workspace-card ledger"><div className="toolbar"><label><MagnifyingGlass/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索产品编号或名称"/></label><select value={filter} onChange={e => setFilter(e.target.value)}><option>全部</option><option>评价中</option><option>待补数</option><option>已归档</option></select></div><table><thead><tr><th>产品</th><th>类型</th><th>生态评分</th><th>状态</th><th>更新时间</th></tr></thead><tbody>{rows.map(p => <tr className={selected.id === p.id ? 'selected' : ''} key={p.id} onClick={() => setSelected(p)}><td><b>{p.name}</b><small>{p.id}</small></td><td>{p.type}</td><td>{p.score === '—' ? '—' : <strong>{p.score}</strong>}</td><td><Tag state={p.state === '评价中' ? 'good' : p.state === '待补数' ? 'warn' : 'neutral'}>{p.state}</Tag></td><td>{p.updated}</td></tr>)}</tbody></table>{!rows.length && <Empty icon={Cube} title="未找到匹配产品" detail="调整筛选条件，或创建一个产品草稿。"/>}</article><article className="workspace-card detail-card"><div className="card-kicker"><Cube weight="fill"/>已选产品</div><h2>{selected.name}</h2><code>{selected.id}</code><div className="detail-stats"><span><b>{selected.score}</b><small>生态评分</small></span><span><b>4 / 4</b><small>指标字段组</small></span><span><b>{selected.state}</b><small>当前状态</small></span></div><div className="summary-box"><b>指标摘要</b><p>展示材料、制造、使用与回收四类摘要指标；不展示产品原始属性和敏感字段。</p></div><button className="primary full" onClick={onEvaluate}><Sparkle weight="fill"/>进入生态评价</button></article></section></>
}

function DataWorkspace() {
  const [packs, setPacks] = useState(dataPacks); const [feedback, setFeedback] = useState(''); const [selected, setSelected] = useState(0)
  const validate = index => { setPacks(packs.map((p, i) => i === index ? [...p.slice(0, 4), '已校验', p[5]] : p)); setFeedback(`“${packs[index][0]}”已在本地沙箱完成格式与完整度校验。`) }
  return <><PageHead eyebrow="DATA PACKAGE" title="数据管理" description="按数据包提交、校验并分级处理进入沙箱的产品数据。" action={<button className="primary" onClick={() => setFeedback('模拟数据包已提交，等待数据管理员补充字段。')}><UploadSimple weight="bold"/>提交数据包</button>}/>{feedback && <Notice>{feedback}</Notice>}<section className="data-layout"><article className="workspace-card pack-list"><div className="card-title"><div><Database weight="fill"/><h2>数据包与字段组</h2></div><span>不直接展示敏感原始值</span></div>{packs.map((p, i) => { const [name, fields, completeness, sensitivity, status, I] = p; return <button key={name} className={`pack-row ${selected === i ? 'picked' : ''}`} onClick={() => setSelected(i)}><span className="pack-icon"><I weight="fill"/></span><span className="pack-copy"><b>{name}</b><small>{fields} · {sensitivity}数据</small></span><span className="completion"><i><em style={{width:`${completeness}%`}}/></i><b>{completeness}%</b></span><Tag state={status === '已校验' ? 'good' : 'warn'}>{status}</Tag></button>})}</article><article className="workspace-card data-inspector"><div className="card-kicker"><SlidersHorizontal weight="fill"/>数据包检查器</div><h2>{packs[selected][0]}</h2><p>字段级校验不会将原始数值复制到界面或链上，仅产生完整度、校验结论和数据摘要哈希。</p><dl><div><dt>当前完整度</dt><dd>{packs[selected][2]}%</dd></div><div><dt>敏感级别</dt><dd>{packs[selected][3]}</dd></div><div><dt>校验规则</dt><dd>Schema v1.3</dd></div><div><dt>数据摘要</dt><dd><code>sha256: 8f3a…7c21</code></dd></div></dl><button className="secondary full" onClick={() => validate(selected)}><SealCheck weight="bold"/>执行完整性校验</button></article></section></>
}

function Labels({ label }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(null); const [filter, setFilter] = useState('全部'); const [feedback, setFeedback] = useState('')
  useEffect(() => { let live = true; fetch('/api/eco/labels', {headers}).then(r => r.ok ? r.json() : Promise.reject()).then(b => { if (live) setItems(normalizeList(b).map(normalizeLabel).filter(Boolean)) }).catch(() => live && setItems(fallbackLabels.map(normalizeLabel).filter(Boolean))).finally(() => live && setLoading(false)); return () => {live = false} }, [label.id])
  const rows = useMemo(() => { const localLabel = normalizeLabel({...label, status: 'PENDING', productName: '氢能储能一体机 HES-1000'}); const merged = localLabel && !items.some(x => x.id === localLabel.id) ? [localLabel, ...items] : items; return (filter === '全部' ? merged : merged.filter(x => (x.status || 'PENDING') === filter)).filter(x => x.id) }, [items, label, filter])
  const current = rows.find(item => item.id === selected?.id) || rows[0]
  async function revoke() { if (!current) return; try { const r = await fetch(`/api/eco/labels/${encodeURIComponent(current.id)}/revoke`, {method:'POST',headers,body:'{}'}); if (!r.ok) throw Error(); setItems(xs => xs.map(x => x.id === current.id ? {...x,status:'REVOKED'} : x)); setSelected({...current,status:'REVOKED'}); setFeedback(`演示环境已撤销 ${current.id}；此操作不代表真实链上交易。`) } catch { setFeedback('撤销请求未完成；当前仍为本地演示状态。') } }
  async function copy() { try { await navigator.clipboard.writeText(current.id); setFeedback(`已复制标识编号 ${current.id}`) } catch { setFeedback('无法访问剪贴板，请手动复制标识编号。') } }
  return <><PageHead eyebrow="ISSUED LABELS" title="标识管理" description="查询、验证与管理生态设计数字标识；链上状态单独呈现。" action={<button className="secondary" onClick={() => setFeedback('验证入口已准备好，可从右侧查看标识验证信息。')}><ShieldCheck weight="bold"/>查看验证说明</button>}/>{feedback && <Notice kind={feedback.includes('未完成') ? 'warning' : 'success'}>{feedback}</Notice>}<section className="labels-layout"><article className="workspace-card label-table"><div className="toolbar"><div className="segmented">{['全部','PENDING','REVOKED'].map(x => <button className={filter === x ? 'on' : ''} key={x} onClick={() => setFilter(x)}>{x}</button>)}</div><span className="count">{loading ? '正在读取…' : `${rows.length} 个标识`}</span></div>{!loading && !rows.length ? <Empty icon={QrCode} title="暂无此状态的标识" detail="签发成功后，标识会出现在这里。"/> : <div className="label-list">{rows.map(item => <button className={current?.id === item.id ? 'chosen' : ''} key={item.id} onClick={() => setSelected(item)}><QrCode weight="fill"/><span><b>{item.id}</b><small>{item.productName || '产品名称受权限保护'}</small></span><Tag state={item.status === 'REVOKED' ? 'danger' : 'warn'}>{item.status || 'PENDING'}</Tag><strong>{item.level || '—'}</strong></button>)}</div>}</article>{current && <article className="workspace-card label-preview"><div className="label-seal"><Leaf weight="fill"/><span>生态设计数字标识<small>DEMO ENVIRONMENT</small></span><Tag state={current.status === 'REVOKED' ? 'danger' : 'warn'}>{current.status || 'PENDING'}</Tag></div><div className="label-qr"><QRCodeSVG value={`${window.location.origin}/verify/${current.id}`} size={110}/><div><b>{current.id}</b><p>二维码可用于验证编号和公开摘要；当前链上状态为演示 PENDING。</p></div></div><div className="label-actions"><button className="secondary" onClick={copy}><Copy/>复制编号</button><button className="danger-button" disabled={current.status === 'REVOKED'} onClick={revoke}><Trash/>演示撤销</button></div></article>}</section></>
}

function Assessments({ onEvaluate }) {
  const [tasks, setTasks] = useState([]); const [algorithms, setAlgorithms] = useState([]); const [filters, setFilters] = useState({ status: '全部', algorithm: '全部', version: '全部', score: '全部' }); const [loading, setLoading] = useState(true)
  useEffect(() => { let live = true; Promise.all([
    fetch('/api/eco/evaluations', {headers}).then(r => r.ok ? r.json() : Promise.reject()),
    fetch('/api/eco/algorithms', {headers}).then(r => r.ok ? r.json() : Promise.reject()),
  ]).then(([taskBody, algorithmBody]) => { if (live) { setTasks(normalizeList(taskBody)); setAlgorithms(normalizeList(algorithmBody)) } }).catch(() => { if (live) { setTasks(fallbackTasks); setAlgorithms([{id:'green-cycle',name:'GreenCycle',version:'2.4',status:'ACTIVE'}]) } }).finally(() => live && setLoading(false)); return () => {live=false} }, [])
  const versions = [...new Set(tasks.map(t => t.algorithmVersion || t.algorithm?.version).filter(Boolean))]
  const rows = tasks.filter(t => { const version = t.algorithmVersion || t.algorithm?.version || 'GreenCycle v2.4'; const algorithm = t.algorithmName || t.algorithm?.name || 'GreenCycle'; const score = Number(t.score); return (filters.status === '全部' || (t.status || '').toUpperCase() === filters.status) && (filters.algorithm === '全部' || algorithm === filters.algorithm) && (filters.version === '全部' || version === filters.version) && (filters.score === '全部' || (filters.score === '80+' ? score >= 80 : score < 80)) })
  const setFilter = (key, value) => setFilters(current => ({...current, [key]: value}))
  return <><PageHead eyebrow="SANDBOX ASSESSMENT" title="生命周期评估" description="运行可信沙箱中的加权算法，评价输入和敏感字段不离开沙箱。" action={<button className="primary" onClick={onEvaluate}><Plus weight="bold"/>新建评价</button>}/><section className="assessment-kpis"><article><Sparkle weight="fill"/><span><small>可用算法</small><b>{loading ? '读取中' : `${algorithms.length || 1} 个版本`}</b></span></article><article><ClipboardText weight="fill"/><span><small>任务队列</small><b>{loading ? '—' : tasks.length}</b></span></article><article><LockKey weight="fill"/><span><small>计算位置</small><b>本地沙箱</b></span></article></section><article className="workspace-card task-board"><div className="board-head"><div><h2>评价任务队列</h2><small>任务与算法版本由 API 读取；无服务时显示本地演示数据。</small></div><button className="icon-button" onClick={() => setFilters({status:'全部',algorithm:'全部',version:'全部',score:'全部'})} title="清除筛选"><Funnel/></button></div><div className="task-filters"><select value={filters.status} onChange={e => setFilter('status', e.target.value)}><option>全部</option><option>COMPLETED</option><option>DRAFT</option></select><select value={filters.algorithm} onChange={e => setFilter('algorithm', e.target.value)}><option>全部</option>{[...new Set(algorithms.map(a => a.name).filter(Boolean).concat(tasks.map(t => t.algorithmName || t.algorithm?.name).filter(Boolean)))].map(x => <option key={x}>{x}</option>)}</select><select value={filters.version} onChange={e => setFilter('version', e.target.value)}><option>全部</option>{versions.map(x => <option key={x}>{x}</option>)}</select><select value={filters.score} onChange={e => setFilter('score', e.target.value)}><option>全部</option><option>80+</option><option>80 以下</option></select></div>{!loading && !rows.length ? <Empty icon={ClipboardText} title="没有匹配的评价任务" detail="调整筛选条件，或新建一项评价。" action={<button className="primary" onClick={onEvaluate}><Plus/>新建评价</button>}/> : <div className="task-rows">{rows.map(t => <div key={t.id}><span className={`task-progress ${t.status === 'COMPLETED' ? 'complete' : ''}`}><i style={{width:t.status === 'COMPLETED'?'100%':'28%'}}/></span><section><b>{t.productName || t.product?.productName || '受限产品'}</b><small>{t.id}</small></section><section><small>算法版本</small><b>{t.algorithmVersion || t.algorithm?.version || 'GreenCycle v2.4'}</b></section><section><small>评分</small><b>{t.score ?? '待计算'}</b></section><Tag state={t.status === 'COMPLETED' ? 'good' : 'warn'}>{t.status || 'DRAFT'}</Tag><button className="icon-button" onClick={onEvaluate} title="复用为新评价"><ArrowClockwise/></button></div>)}</div>}</article></>
}

function ChainEvidence() {
  const [tab, setTab] = useState('结果锚定'); const [feedback, setFeedback] = useState('')
  const entries = { '算法注册': ['AlgorithmRegistry', 'GreenCycle v2.4', '0xe791…3a0f', '算法版本、指标权重摘要'], '结果锚定': ['EcoLabelRegistry', 'ECO-HES-0842', '0x4d92…9ab0', '计算结果摘要哈希'], '标识状态': ['EcoLabelRegistry', 'PENDING', '0x0000…0000', '签发与撤销状态'] }
  const value = entries[tab]
  return <><PageHead eyebrow="ON-CHAIN EVIDENCE" title="链上存证" description="展示应由合约登记的可验证摘要；当前运行的是内存账本演示适配器。" action={<button className="secondary" onClick={() => setFeedback('已刷新本地演示账本。真实 AntChain 回执需由生产适配器返回。')}><ArrowClockwise/>刷新记录</button>}/>{feedback && <Notice>{feedback}</Notice>}<section className="chain-layout"><article className="workspace-card contract-card"><div className="card-kicker"><LockKey weight="fill"/>合约语义边界</div><h2>可信对象登记，而非原始产品数据上链</h2><div className="contract-list">{Object.entries(entries).map(([name, v]) => <button key={name} className={tab === name ? 'active-contract' : ''} onClick={() => setTab(name)}><span><SealCheck weight="fill"/></span><div><b>{name}</b><small>{v[0]} · {v[3]}</small></div><Tag state="warn">PENDING</Tag></button>)}</div></article><article className="workspace-card record-card"><div className="record-top"><div><small>CONTRACT</small><h2>{value[0]}</h2></div><Tag state="warn">演示 PENDING</Tag></div><dl><div><dt>登记对象</dt><dd>{value[1]}</dd></div><div><dt>交易哈希</dt><dd><code>{value[2]}</code></dd></div><div><dt>区块高度</dt><dd>待确认</dd></div><div><dt>存证内容</dt><dd>{value[3]}</dd></div></dl><div className="chain-timeline"><span><i/><b>本地生成摘要</b><small>09:43 · 可复现计算结果</small></span><span><i/><b>已提交演示适配器</b><small>09:43 · 内存账本记录</small></span><span className="pending-node"><i/><b>等待真实链回执</b><small>不将 PENDING 表述为上链成功</small></span></div></article></section></>
}

function Permissions() {
  const [role, setRole] = useState('公开'); const [feedback, setFeedback] = useState(''); const rules = [['标识编号','●','●','●','●'],['等级与公开摘要','●','●','●','●'],['算法版本','—','●','●','●'],['数据包完整度','—','●','●','●'],['数据摘要哈希','—','—','●','●'],['敏感原始字段','—','—','●','监管授权']]
  const index = ['公开','合作伙伴','企业内部','监管机构'].indexOf(role) + 1
  return <><PageHead eyebrow="ACCESS POLICY" title="权限管理" description="以最小权限展示可验证结论；敏感原始字段只留在企业与授权监管视角。" action={<button className="primary" onClick={() => setFeedback(`“${role}”视图策略已保存到本地演示环境。`)}><FloppyDisk weight="bold"/>保存策略</button>}/>{feedback && <Notice>{feedback}</Notice>}<section className="permission-layout"><article className="workspace-card matrix-card"><div className="board-head"><h2>字段可见性矩阵</h2><span>● 可见 · — 不可见</span></div><table className="matrix"><thead><tr><th>字段</th>{['公开','合作伙伴','企业内部','监管机构'].map(x => <th className={role === x ? 'active-col' : ''} key={x}>{x}</th>)}</tr></thead><tbody>{rules.map(r => <tr key={r[0]}><td>{r[0]}</td>{r.slice(1).map((v,i) => <td className={i + 1 === index ? 'active-col' : ''} key={i}>{v}</td>)}</tr>)}</tbody></table></article><article className="workspace-card role-preview"><div className="card-kicker"><Eye weight="fill"/>视图预览</div><div className="role-switch">{['公开','合作伙伴','企业内部','监管机构'].map(x => <button className={role === x ? 'current' : ''} key={x} onClick={() => setRole(x)}>{x}</button>)}</div><h2>{role}可见内容</h2><div className="preview-lines"><p><CheckCircle weight="fill"/>ECO-HES-0842 · A 级 · 84.2</p>{index > 1 && <p><CheckCircle weight="fill"/>算法 GreenCycle v2.4 · 数据完整度 92%</p>}{index > 2 && <p><CheckCircle weight="fill"/>数据摘要哈希 sha256: 8f3a…7c21</p>}{index > 3 && <p><CheckCircle weight="fill"/>监管授权记录与字段访问日志</p>}<p className="restricted"><LockKey weight="fill"/>敏感原始属性不在公开标识中展示</p></div></article></section></>
}

function Settings() {
  const [settings, setSettings] = useState({ sandbox: true, adapter: false, notify: true, retain: '180 天' }); const [saved, setSaved] = useState(false)
  const toggle = key => setSettings(s => ({...s,[key]:!s[key]}))
  return <><PageHead eyebrow="SYSTEM CONFIGURATION" title="系统设置" description="配置沙箱处理、链适配器、通知和数据保留策略。" action={<button className="primary" onClick={() => setSaved(true)}><FloppyDisk weight="bold"/>保存设置</button>}/>{saved && <Notice>设置已保存到本地演示配置；未向外部链服务发送请求。</Notice>}<section className="settings-layout"><article className="workspace-card settings-group"><h2>运行环境</h2><Setting icon={Cube} title="可信计算沙箱" text="评价输入、敏感字段与可复现计算均在本地沙箱处理。" checked={settings.sandbox} onChange={() => toggle('sandbox')}/><Setting icon={LockKey} title="AntChain 适配器" text="当前为内存账本演示适配器；启用前需配置真实凭据和回执校验。" checked={settings.adapter} onChange={() => toggle('adapter')}/></article><article className="workspace-card settings-group"><h2>治理策略</h2><Setting icon={BellIcon} title="状态通知" text="任务失败、校验告警和链上回执变更时通知管理员。" checked={settings.notify} onChange={() => toggle('notify')}/><div className="setting-select"><span><Archive weight="fill"/><p><b>数据保留期</b><small>到期后仅保留可验证的摘要与审计记录。</small></p></span><select value={settings.retain} onChange={e => setSettings(s => ({...s,retain:e.target.value}))}><option>90 天</option><option>180 天</option><option>365 天</option></select></div></article><article className="workspace-card safeguard"><ShieldCheck weight="fill"/><h2>安全边界检查</h2><p>当前界面会将“本地完整性校验通过”与“真实链上确认”分开表达。</p><ul><li>不将原始产品属性存入标识或账本</li><li>不将 PENDING 标为链上成功</li><li>按角色过滤可见字段</li></ul></article></section></>
}
function BellIcon(props) { return <Info {...props}/> }
function Setting({ icon: I, title, text, checked, onChange }) { return <div className="setting"><I weight="fill"/><p><b>{title}</b><small>{text}</small></p><button className={`switch ${checked?'checked':''}`} onClick={onChange} aria-label={`${title}${checked?'已启用':'已关闭'}`}><i/></button></div> }

export function Workspace({ active, label, onEvaluate }) {
  if (active === '产品管理') return <Products onEvaluate={onEvaluate}/>
  if (active === '数据管理') return <DataWorkspace/>
  if (active === '标识管理') return <Labels label={label}/>
  if (active === '生命周期评估') return <Assessments onEvaluate={onEvaluate}/>
  if (active === '链上存证') return <ChainEvidence/>
  if (active === '权限管理') return <Permissions/>
  return <Settings/>
}
